<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class levelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('levels')->insert(['name' => '1', 'points' => '200', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '2', 'points' => '400', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '3', 'points' => '500', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '4', 'points' => '600', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '5', 'points' => '700', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '6', 'points' => '800', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '7', 'points' => '900', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '8', 'points' => '1000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '9', 'points' => '1000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '10', 'points' => '2000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '11', 'points' => '2000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '12', 'points' => '2000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '13', 'points' => '2000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '14', 'points' => '2000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '15', 'points' => '3000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '16', 'points' => '3000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '17', 'points' => '3000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '18', 'points' => '3000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '19', 'points' => '3000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '20', 'points' => '5000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '21', 'points' => '5000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '22', 'points' => '5000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '23', 'points' => '5000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '24', 'points' => '5000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '25', 'points' => '7000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '26', 'points' => '7000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '27', 'points' => '7000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '28', 'points' => '7000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '29', 'points' => '7000', 'coins' => '500',]);
        DB::table('levels')->insert(['name' => '30', 'points' => '9000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '31', 'points' => '9000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '32', 'points' => '9000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '33', 'points' => '9000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '34', 'points' => '9000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '35', 'points' => '10000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '36', 'points' => '10000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '37', 'points' => '10000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '38', 'points' => '10000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '39', 'points' => '10000', 'coins' => '2000',]);
        DB::table('levels')->insert(['name' => '40', 'points' => '12000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '41', 'points' => '12000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '42', 'points' => '12000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '43', 'points' => '12000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '44', 'points' => '12000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '45', 'points' => '14000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '46', 'points' => '14000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '47', 'points' => '14000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '48', 'points' => '14000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '49', 'points' => '14000', 'coins' => '3000',]);
        DB::table('levels')->insert(['name' => '50', 'points' => '15000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '51', 'points' => '15000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '52', 'points' => '15000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '53', 'points' => '15000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '54', 'points' => '15000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '55', 'points' => '18000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '56', 'points' => '18000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '57', 'points' => '18000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '58', 'points' => '18000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '59', 'points' => '18000', 'coins' => '5000',]);
        DB::table('levels')->insert(['name' => '60', 'points' => '20000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '61', 'points' => '20000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '62', 'points' => '20000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '63', 'points' => '20000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '64', 'points' => '20000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '65', 'points' => '22000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '66', 'points' => '22000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '67', 'points' => '22000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '68', 'points' => '22000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '69', 'points' => '22000', 'coins' => '8000',]);
        DB::table('levels')->insert(['name' => '70', 'points' => '25000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '71', 'points' => '25000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '72', 'points' => '25000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '73', 'points' => '25000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '74', 'points' => '25000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '75', 'points' => '27000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '76', 'points' => '27000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '77', 'points' => '27000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '78', 'points' => '27000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '79', 'points' => '27000', 'coins' => '10000',]);
        DB::table('levels')->insert(['name' => '80', 'points' => '28000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '81', 'points' => '28000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '82', 'points' => '28000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '83', 'points' => '28000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '84', 'points' => '28000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '84', 'points' => '28000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '85', 'points' => '30000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '86', 'points' => '30000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '87', 'points' => '30000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '88', 'points' => '30000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '89', 'points' => '30000', 'coins' => '12000',]);
        DB::table('levels')->insert(['name' => '90', 'points' => '32000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '91', 'points' => '32000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '92', 'points' => '32000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '93', 'points' => '32000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '94', 'points' => '32000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '95', 'points' => '33000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '96', 'points' => '33000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '97', 'points' => '33000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '98', 'points' => '33000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '99', 'points' => '33000', 'coins' => '15000',]);
        DB::table('levels')->insert(['name' => '100', 'points' => '35000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '101', 'points' => '35000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '102', 'points' => '35000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '103', 'points' => '35000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '104', 'points' => '35000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '105', 'points' => '36000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '106', 'points' => '36000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '107', 'points' => '36000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '108', 'points' => '36000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '109', 'points' => '36000', 'coins' => '20000',]);
        DB::table('levels')->insert(['name' => '110', 'points' => '38000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '111', 'points' => '38000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '112', 'points' => '38000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '113', 'points' => '38000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '114', 'points' => '38000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '115', 'points' => '40000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '116', 'points' => '40000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '117', 'points' => '40000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '118', 'points' => '40000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '119', 'points' => '40000', 'coins' => '25000',]);
        DB::table('levels')->insert(['name' => '120', 'points' => '42000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '121', 'points' => '42000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '122', 'points' => '42000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '123', 'points' => '42000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '124', 'points' => '42000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '125', 'points' => '44000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '126', 'points' => '44000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '127', 'points' => '44000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '128', 'points' => '44000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '129', 'points' => '44000', 'coins' => '30000',]);
        DB::table('levels')->insert(['name' => '130', 'points' => '45000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '131', 'points' => '45000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '132', 'points' => '45000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '133', 'points' => '45000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '134', 'points' => '45000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '135', 'points' => '47000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '136', 'points' => '47000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '137', 'points' => '47000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '138', 'points' => '47000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '139', 'points' => '47000', 'coins' => '40000',]);
        DB::table('levels')->insert(['name' => '140', 'points' => '48000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '141', 'points' => '48000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '142', 'points' => '48000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '143', 'points' => '48000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '144', 'points' => '48000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '145', 'points' => '50000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '146', 'points' => '50000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '147', 'points' => '50000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '148', 'points' => '50000', 'coins' => null,]);
        DB::table('levels')->insert(['name' => '149', 'points' => '50000', 'coins' => '50000',]);
    }
}
