<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class VipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('vip_tiers')->insert([
            'name' => 'Vip1',
            'price' => '7000',
            'renew_price' => '5250',
            'privileges' => json_encode(
                [
                    "vip_logo" => 1,
                    "vip_logo_value" => 1,
                    "vip_logo_desc_ar" => "يظهر شعار vip 1 داخل الغرفة في البروفيل او بالترتيب او بالاعضاء", // logo
                    "vip_logo_desc_en" => "", // logo
                    "vip_mic_border" => 1,
                    "vip_mic_border_value" => 1,
                    "vip_mic_border_desc_ar" => "يظهر إطار الميك عند صعود المستخدم علي الميك او بالبروفيل او بالتكست او بالرسائل", // mic border
                    "vip_mic_border_desc_en" => 1, // mic border
                    "topLevel" =>1,
                    "topLevel_value" =>1,
                    "topLevel_desc_ar" =>"الترتيب في الصف الأمامي لقائمة المستخدمين في الغرفة", // toplevel
                    "topLevel_desc_en" =>1, // toplevel
                    "commission_gift" => 1,
                    "commission_gift_value" => 2.5,
                    "commission_gift_desc_ar" => "يمكن لمالك الغرفة الحصول على 2.5% نسبة من الهدايا المرسلة داخل الغرفة", // gift commission from room
                    "commission_gift_desc_en" => 2.5, // gift commission from room
                    "entrance_effect" => 1,
                    "entrance_effect_value" => 1,
                    "entrance_effect_desc_ar" => "يمكنك إظهار تأثيرات الدخول عند الدخول لأي غرفة", // entrance effect
                    "entrance_effect_desc_en" => 1, // entrance effect
                    "colored_name" => 1,
                    "colored_name_value" => 1,
                    "colored_name_desc_ar" => "يكون اسم المستخدم بنفس لون هذه الاستقراطية علي حسب الاختيار", // colored_name
                    "colored_name_desc_en" => 1, // colored_name
                    "special_gift" => 1,
                    "special_gift_value" => 0,
                    "special_gift_count" => 0,
                    "special_gift_desc_ar" => "يحصل المستخدم علي هدية خاصة ( تاج ) بقيمة 299 كوينز عدد 3 تاج", // special gift
                    "special_gift_desc_en" => 0, // special gift
                    "arsto_card" => 1,
                    "arsto_card_value" => 1,
                    "arsto_card_desc_ar" => "بطاقة الأرستقراطي في الغرفة ( شكل البروفيل في الغرفة )", // arsto card desc
                    "arsto_card_desc_en" => "1", // arsto card desc
                    "vip_vehicle" => 0,
                    "vip_vehicle_value" => 0,
                    "vip_vehicle_desc_ar" => "", // vehicle
                    "vip_vehicle_desc_en" => "", // vehicle
                    "colored_messages" => 0,
                    "colored_messages_value" => 0,
                    "colored_messages_desc_ar" => "", // colored_message
                    "colored_messages_desc_en" => "", // colored_message
                    "room_password"=> 0,
                    "room_password_value"=> 0,
                    "room_password_desc_ar"=> "", // room password
                    "room_password_desc_en"=> "", // room password
                    "anti-kick" => 0,
                    "anti-kick_value" => 0,
                    "anti-kick_desc_ar" => "", // anti kick
                    "anti-kick_desc_en" => "", // anti kick
                    "hide_country" => 0,
                    "hide_country_value" => 0,
                    "hide_country_desc_ar" => "", // hide country
                    "hide_country_desc_en" => "", // hide country
                    "anti-ban-chat"=> 0,
                    "anti-ban-chat_value"=> 0,
                    "anti-ban-chat_desc_ar"=> "", // ban chat
                    "anti-ban-chat_desc_en"=> "", // ban chat
                    "exp" => 0,
                    "exp_value" => 0,
                    "exp_value_desc_ar" => "", // exp % gain
                    "exp_value_desc_en" => "", // exp % gain
                    "support_first" => 0,
                    "support_value" => 0,
                    "support_desc_ar" => "",  // support desc
                    "support_desc_en" => "",  // support desc
                    "upload_background" => 0,
                    "upload_background_value" => 0,
                    "upload_background_desc_ar" => "", // upload background desc
                    "upload_background_desc_en" => "", // upload background desc
                    "daily_login_reward" => 0,
                    "daily_login_reward_value" => 0,
                    "daily_login_reward_desc_ar" => "",
                    "daily_login_reward_desc_en" => "",
                ]
            )
        ]);
        DB::table('vip_tiers')->insert([
            'name' => 'Vip2',
            'price' => '20000',
            'renew_price' => '15000',
            'privileges' => json_encode(
                [
                    "vip_logo" => 1,
                    "vip_logo_value" => 1,
                    "vip_logo_desc_ar" => "يظهر شعار vip 2 داخل الغرفة في البروفيل او بالترتيب او بالاعضاء", // logo
                    "vip_logo_desc_en" => "", // logo
                    "vip_mic_border" => 1,
                    "vip_mic_border_value" => 1,
                    "vip_mic_border_desc_ar" => "يظهر إطار الميك عند صعود المستخدم علي الميك او بالبروفيل او بالتكست او بالرسائل  ", // mic border
                    "vip_mic_border_desc_en" => "", // mic border
                    "topLevel" =>1,
                    "topLevel_value" =>1,
                    "topLevel_desc_ar" =>"الترتيب في الصف الأمامي لقائمة المستخدمين في الغرفة", // toplevel
                    "topLevel_desc_en" =>"", // toplevel
                    "commission_gift" => 1,
                    "commission_gift_value" => 3,
                    "commission_gift_desc_ar" => "يمكن لمالك الغرفة الحصول على3% نسبة من الهدايا المرسلة داخل الغرفة", // gift commission from room
                    "commission_gift_desc_en" => "", // gift commission from room
                    "entrance_effect" => 1,
                    "entrance_effect_value" => 1,
                    "entrance_effect_desc_ar" => "يمكنك إظهار تأثيرات الدخول عند الدخول لأي غرفة", // entrance effect
                    "entrance_effect_desc_en" => 1, // entrance effect
                    "colored_name" => 1,
                    "colored_name_value" => 1,
                    "colored_name_desc_ar" => "يكون اسم المستخدم بنفس لون هذه الاستقراطية علي حسب الاختيار", // colored_name
                    "colored_name_desc_en" => 1, // colored_name
                    "special_gift" => 1,
                    "special_gift_value" => 0,
                    "special_gift_count" => 0,
                    "special_gift_desc_ar" => "يحصل المستخدم علي هدية خاصة ( تاج ) بقيمة 299 كوينز عدد( 5 تاج )", // special gift
                    "special_gift_desc_en" => 0, // special gift
                    "arsto_card" => 1,
                    "arsto_card_value" => 1,
                    "arsto_card_desc_ar" => "بطاقة الأرستقراطي في الغرفة ( شكل البروفيل في الغرفة )", // arsto card desc
                    "arsto_card_desc_en" => "1", // arsto card desc
                    "colored_messages" => 1,
                    "colored_messages_value" => 0,
                    "colored_messages_desc_ar" => "الرسائل التي أرسلت ستكون ملونة ( فقاعات الدردشة )", // colored_message
                    "colored_messages_desc_en" => "", // colored_message
                    "exp" => 1,
                    "exp_value" => 1.1,
                    "exp_value_desc_ar" => "1.1 مرة زيادة في نقاط الخبرة", // exp % gain
                    "exp_value_desc_en" => "", // exp % gain
                    "vip_vehicle" => 0,
                    "vip_vehicle_value" => 0,
                    "vip_vehicle_desc_ar" => "", // vehicle
                    "vip_vehicle_desc_en" => "", // vehicle
                    "room_password"=> 0,
                    "room_password_value"=> 0,
                    "room_password_desc_ar"=> "", // room password
                    "room_password_desc_en"=> "", // room password
                    "anti-kick" => 0,
                    "anti-kick_value" => 0,
                    "anti-kick_desc_ar" => "", // anti kick
                    "anti-kick_desc_en" => "", // anti kick
                    "hide_country" => 0,
                    "hide_country_value" => 0,
                    "hide_country_desc_ar" => "", // hide country
                    "hide_country_desc_en" => "", // hide country
                    "anti-ban-chat"=> 0,
                    "anti-ban-chat_value"=> 0,
                    "anti-ban-chat_desc_ar"=> "", // ban chat
                    "anti-ban-chat_desc_en"=> "", // ban chat
                    "support_first" => 0,
                    "support_value" => 0,
                    "support_desc_ar" => "",  // support desc
                    "support_desc_en" => "",  // support desc
                    "upload_background" => 0,
                    "upload_background_value" => 0,
                    "upload_background_desc_ar" => "", // upload background desc
                    "upload_background_desc_en" => "", // upload background desc
                    "daily_login_reward" => 1,
                    "daily_login_reward_value" => 300,
                    "daily_login_reward_desc_ar" => "",
                    "daily_login_reward_desc_en" => "",
                ]
            )
        ]);
        DB::table('vip_tiers')->insert([
            'name' => 'Vip3',
            'price' => '66000',
            'renew_price' => '49500',
            'privileges' => json_encode(
                [
                    "vip_logo" => 1,
                    "vip_logo_value" => 1,
                    "vip_logo_desc_ar" => "يظهر شعار vip 3 داخل الغرفة في البروفيل او بالترتيب او بالاعضاء", // logo
                    "vip_logo_desc_en" => 1, // logo
                    "vip_mic_border" => 1,
                    "vip_mic_border_value" => 1,
                    "vip_mic_border_desc_ar" => "يظهر إطار الميك عند صعود المستخدم علي الميك او بالبروفيل او بالتكست او بالرسائل", // mic border
                    "vip_mic_border_desc_en" => 1, // mic border
                    "topLevel" =>1,
                    "topLevel_value" =>1,
                    "topLevel_desc_ar" =>"الترتيب في الصف الأمامي لقائمة المستخدمين في الغرفة ", // toplevel
                    "topLevel_desc_en" =>1, // toplevel
                    "commission_gift" => 1,
                    "commission_gift_value" => 2.5,
                    "commission_gift_desc_ar" => "يمكن لمالك الغرفة الحصول على 3.5% نسبة من الهدايا المرسلة داخل الغرفة", // gift commission from room
                    "commission_gift_desc_en" => 2.5, // gift commission from room
                    "entrance_effect" => 1,
                    "entrance_effect_value" => 1,
                    "entrance_effect_desc_ar" => "يمكنك إظهار تأثيرات الدخول عند الدخول لأي غرفة", // entrance effect
                    "entrance_effect_desc_en" => 1, // entrance effect
                    "colored_name" => 1,
                    "colored_name_value" => 1,
                    "colored_name_desc_ar" => "يكون اسم المستخدم بنفس لون هذه الاستقراطية علي حسب الاختيار", // colored_name
                    "colored_name_desc_en" => 1, // colored_name
                    "special_gift" => 1,
                    "special_gift_value" => 0,
                    "special_gift_count" => 5,
                    "special_gift_desc_ar" => "يحصل المستخدم علي هدية خاصة ( تاج ) بقيمة 299 كوينز عدد 5 تاج", // special gift
                    "special_gift_desc_en" => 0, // special gift
                    "arsto_card" => 1,
                    "arsto_card_value" => 1,
                    "arsto_card_desc_ar" => "بطاقة الأرستقراطي في الغرفة ( شكل البروفيل في الغرفة )", // arsto card desc
                    "arsto_card_desc_en" => "1", // arsto card desc
                    "vip_vehicle" => 1,
                    "vip_vehicle_value" => 0,
                    "vip_vehicle_desc_ar" => "يمكنك إظهار هذه المركبة عند دخول الغرفة، يمكنك تعديل ذلك في خزنة الزينة", // vehicle
                    "vip_vehicle_desc_en" => "", // vehicle
                    "colored_messages" => 1,
                    "colored_messages_value" => 0,
                    "colored_messages_desc_ar" => "الرسائل التي أرسلت ستكون ملونة ( فقاعات الدردشة)", // colored_message
                    "colored_messages_desc_en" => "", // colored_message
                    "room_password"=> 1,
                    "room_password_value"=> 0,
                    "room_password_desc_ar"=> "يمكن لمالك الغرفة اغلاق غرفته بالرقم السري المكون من  6 ارقام", // room password
                    "room_password_desc_en"=> "", // room password
                    "hide_country" => 1,
                    "hide_country_value" => 0,
                    "hide_country_desc_ar" => "سيتم إظهار دولتك كغير معروفة في صفحتك الشخصية", // hide country
                    "hide_country_desc_en" => "", // hide country
                    "exp" => 1,
                    "exp_value" => 1.2,
                    "exp_value_desc_ar" => "1.2 مرة زيادة في نقاط الخبرة", // exp % gain
                    "exp_value_desc_en" => "", // exp % gain
                    "daily_login_reward" => 1,
                    "daily_login_reward_value" => 330,
                    "daily_login_reward_desc_ar" => "كوينزات أكثر لتسجيل الدخول اليومي ( 330 كوينز يوميا )",
                    "daily_login_reward_desc_en" => "",
                    "anti-kick" => 0,
                    "anti-kick_value" => 0,
                    "anti-kick_desc_ar" => "", // anti kick
                    "anti-kick_desc_en" => "", // anti kick
                    "anti-ban-chat"=> 0,
                    "anti-ban-chat_value"=> 0,
                    "anti-ban-chat_desc_ar"=> "", // ban chat
                    "anti-ban-chat_desc_en"=> "", // ban chat
                    "support_first" => 0,
                    "support_value" => 0,
                    "support_desc_ar" => "",  // support desc
                    "support_desc_en" => "",  // support desc
                    "upload_background" => 0,
                    "upload_background_value" => 0,
                    "upload_background_desc_ar" => "", // upload background desc
                    "upload_background_desc_en" => "", // upload background desc
                ]
            )
        ]);
        DB::table('vip_tiers')->insert([
            'name' => 'Vip4',
            'price' => '300000',
            'renew_price' => '225000',
            'privileges' => json_encode(
                [
                    "vip_logo" => 1,
                    "vip_logo_value" => 1,
                    "vip_logo_desc_ar" => "يظهر شعار vip 4 داخل الغرفة في البروفيل او بالترتيب او بالاعضاء", // logo
                    "vip_logo_desc_en" => 1, // logo
                    "vip_mic_border" => 1,
                    "vip_mic_border_value" => 1,
                    "vip_mic_border_desc_ar" => "يظهر إطار الميك عند صعود المستخدم علي الميك او بالبروفيل او بالتكست او بالرسائل  ", // mic border
                    "vip_mic_border_desc_en" => 1, // mic border
                    "topLevel" =>1,
                    "topLevel_value" =>1,
                    "topLevel_desc_ar" =>"الترتيب في الصف الأمامي لقائمة المستخدمين في الغرفة", // toplevel
                    "topLevel_desc_en" =>1, // toplevel
                    "commission_gift" => 1,
                    "commission_gift_value" => 4,
                    "commission_gift_desc_ar" => "يمكن لمالك الغرفة الحصول على4% نسبة من الهدايا المرسلة داخل الغرفة", // gift commission from room
                    "commission_gift_desc_en" => 2.5, // gift commission from room
                    "entrance_effect" => 1,
                    "entrance_effect_value" => 1,
                    "entrance_effect_desc_ar" => "يمكنك إظهار تأثيرات الدخول عند الدخول لأي غرفة", // entrance effect
                    "entrance_effect_desc_en" => 1, // entrance effect
                    "colored_name" => 1,
                    "colored_name_value" => 1,
                    "colored_name_desc_ar" => "يكون اسم المستخدم بنفس لون هذه الاستقراطية علي حسب الاختيار", // colored_name
                    "colored_name_desc_en" => 1, // colored_name
                    "special_gift" => 1,
                    "special_gift_value" => 0,
                    "special_gift_count" => 7,
                    "special_gift_desc_ar" => "يحصل المستخدم علي هدية خاصة ( تاج ) بقيمة 299 كوينز عدد 7 تاج", // special gift
                    "special_gift_desc_en" => 0, // special gift
                    "arsto_card" => 1,
                    "arsto_card_value" => 1,
                    "arsto_card_desc_ar" => "بطاقة الأرستقراطي في الغرفة ( شكل البروفيل في الغرفة )", // arsto card desc
                    "arsto_card_desc_en" => "1", // arsto card desc
                    "vip_vehicle" => 1,
                    "vip_vehicle_value" => 0,
                    "vip_vehicle_desc_ar" => "يمكنك إظهار هذه المركبة عند دخول الغرفة، يمكنك تعديل ذلك في خزنة الزينة", // vehicle
                    "vip_vehicle_desc_en" => "", // vehicle
                    "colored_messages" => 1,
                    "colored_messages_value" => 0,
                    "colored_messages_desc_ar" => "الرسائل التي أرسلت ستكون ملونة", // colored_message
                    "colored_messages_desc_en" => "", // colored_message
                    "room_password"=> 1,
                    "room_password_value"=> 0,
                    "room_password_desc_ar"=> "يمكن لمالك الغرفة اغلاق غرفته بالرقم السري المكون من  6 ارقام", // room password
                    "room_password_desc_en"=> "", // room password
                    "hide_country" => 1,
                    "hide_country_value" => 0,
                    "hide_country_desc_ar" => "سيتم إظهار دولتك كغير معروفة في صفحتك الشخصية", // hide country
                    "hide_country_desc_en" => "", // hide country
                    "exp" => 1,
                    "exp_value" => 1.3,
                    "exp_value_desc_ar" => "1.3 مرة زيادة في نقاط الخبرة", // exp % gain
                    "exp_value_desc_en" => "", // exp % gain
                    "upload_background" => 1,
                    "upload_background_value" => 0,
                    "upload_background_desc_ar" => "تحميل الموضوع، ويمكنك استخدام كل الموضوعات مجاناً", // upload background desc
                    "upload_background_desc_en" => "", // upload background desc
                    "daily_login_reward" => 1,
                    "daily_login_reward_value" => 2330,
                    "daily_login_reward_desc_ar" => "كوينزات أكثر لتسجيل الدخول اليومي ( 2330 كوينز يوميا )",
                    "daily_login_reward_desc_en" => "",
                    "anti-kick" => 0,
                    "anti-kick_value" => 0,
                    "anti-kick_desc_ar" => "", // anti kick
                    "anti-kick_desc_en" => "", // anti kick
                    "anti-ban-chat"=> 0,
                    "anti-ban-chat_value"=> 0,
                    "anti-ban-chat_desc_ar"=> "", // ban chat
                    "anti-ban-chat_desc_en"=> "", // ban chat
                    "support_first" => 0,
                    "support_value" => 0,
                    "support_desc_ar" => "",  // support desc
                    "support_desc_en" => "",  // support desc
                ]
            )
        ]);
        DB::table('vip_tiers')->insert([
            'name' => 'Vip5',
            'price' => '600000',
            'renew_price' => '450000',
            'privileges' => json_encode(
                [
                    "vip_logo" => 1,
                    "vip_logo_value" => 1,
                    "vip_logo_desc_ar" => "يظهر شعار vip 5 داخل الغرفة في البروفيل او بالترتيب او بالاعضاء", // logo
                    "vip_logo_desc_en" => 1, // logo
                    "vip_mic_border" => 1,
                    "vip_mic_border_value" => 1,
                    "vip_mic_border_desc_ar" => "يظهر إطار الميك عند صعود المستخدم علي الميك او بالبروفيل او بالتكست او بالرسائل", // mic border
                    "vip_mic_border_desc_en" => 1, // mic border
                    "topLevel" =>1,
                    "topLevel_value" =>1,
                    "topLevel_desc_ar" =>"الترتيب في الصف الأمامي لقائمة المستخدمين في الغرفة", // toplevel
                    "topLevel_desc_en" =>1, // toplevel
                    "commission_gift" => 1,
                    "commission_gift_value" => 4.5,
                    "commission_gift_desc_ar" => "يمكن لمالك الغرفة الحصول على 4.5% نسبة من الهدايا المرسلة داخل الغرفة", // gift commission from room
                    "commission_gift_desc_en" => 2.5, // gift commission from room
                    "entrance_effect" => 1,
                    "entrance_effect_value" => 1,
                    "entrance_effect_desc_ar" => "يمكنك إظهار تأثيرات الدخول عند الدخول لأي غرفة", // entrance effect
                    "entrance_effect_desc_en" => 1, // entrance effect
                    "colored_name" => 1,
                    "colored_name_value" => 1,
                    "colored_name_desc_ar" => "يكون اسم المستخدم بنفس لون هذه الاستقراطية علي حسب الاختيار", // colored_name
                    "colored_name_desc_en" => 1, // colored_name
                    "special_gift" => 1,
                    "special_gift_value" => 0,
                    "special_gift_count" => 9,
                    "special_gift_desc_ar" => "يحصل المستخدم علي هدية خاصة ( تاج ) بقيمة 299 كوينز عدد 9 تاج", // special gift
                    "special_gift_desc_en" => 0, // special gift
                    "arsto_card" => 1,
                    "arsto_card_value" => 1,
                    "arsto_card_desc_ar" => "بطاقة الأرستقراطي في الغرفة ( شكل البروفيل في الغرفة )", // arsto card desc
                    "arsto_card_desc_en" => "1", // arsto card desc
                    "vip_vehicle" => 1,
                    "vip_vehicle_value" => 0,
                    "vip_vehicle_desc_ar" => "يمكنك إظهار هذه المركبة عند دخول الغرفة، يمكنك تعديل ذلك في خزنة الزينة", // vehicle
                    "vip_vehicle_desc_en" => "", // vehicle
                    "colored_messages" => 1,
                    "colored_messages_value" => 0,
                    "colored_messages_desc_ar" => "الرسائل التي أرسلت ستكون ملونة ( فقاعات الدردشة )", // colored_message
                    "colored_messages_desc_en" => "", // colored_message
                    "room_password"=> 1,
                    "room_password_value"=> 0,
                    "room_password_desc_ar"=> "يمكن لمالك الغرفة اغلاق غرفته بالرقم السري المكون من  6 ارقام", // room password
                    "room_password_desc_en"=> "", // room password
                    "hide_country" => 1,
                    "hide_country_value" => 0,
                    "hide_country_desc_ar" => "سيتم إظهار دولتك كغير معروفة في صفحتك الشخصية", // hide country
                    "hide_country_desc_en" => "", // hide country
                    "anti-ban-chat"=> 1,
                    "anti-ban-chat_value"=> 0,
                    "anti-ban-chat_desc_ar"=> "لا يمكن لأي أحد حظرك من الكتابة في الغرفة", // ban chat
                    "anti-ban-chat_desc_en"=> "", // ban chat
                    "exp" => 1,
                    "exp_value" => 1.4,
                    "exp_value_desc_ar" => "1.4 مرة زيادة في نقاط الخبرة", // exp % gain
                    "exp_value_desc_en" => "", // exp % gain
                    "upload_background" => 1,
                    "upload_background_value" => 0,
                    "upload_background_desc_ar" => "تحميل الموضوع، ويمكنك استخدام كل الموضوعات مجاناً", // upload background desc
                    "upload_background_desc_en" => "", // upload background desc
                    "daily_login_reward" => 1,
                    "daily_login_reward_value" => 3330,
                    "daily_login_reward_desc_ar" => "كوينزات أكثر لتسجيل الدخول اليومي ( 3330 كوينز يوميا )",
                    "daily_login_reward_desc_en" => "",
                    "support_first" => 0,
                    "support_value" => 0,
                    "support_desc_ar" => "",  // support desc
                    "support_desc_en" => "",  // support desc
                    "anti-kick" => 0,
                    "anti-kick_value" => 0,
                    "anti-kick_desc_ar" => "", // anti kick
                    "anti-kick_desc_en" => "", // anti kick
                ]
            )
        ]);
        DB::table('vip_tiers')->insert([
            'name' => 'Vip6',
            'price' => '900000',
            'renew_price' => '675000',
            'privileges' => json_encode(
                [
                    "vip_logo" => 1,
                    "vip_logo_value" => 1,
                    "vip_logo_desc_ar" => "يظهر شعار vip 6 داخل الغرفة في البروفيل او بالترتيب او بالاعضاء", // logo
                    "vip_logo_desc_en" => 1, // logo
                    "vip_mic_border" => 1,
                    "vip_mic_border_value" => 1,
                    "vip_mic_border_desc_ar" => "يظهر إطار الميك عند صعود المستخدم علي الميك او بالبروفيل او بالتكست او بالرسائل", // mic border
                    "vip_mic_border_desc_en" => 1, // mic border
                    "topLevel" =>1,
                    "topLevel_value" =>1,
                    "topLevel_desc_ar" =>"الترتيب في الصف الأمامي لقائمة المستخدمين في الغرفة", // toplevel
                    "topLevel_desc_en" =>1, // toplevel
                    "commission_gift" => 1,
                    "commission_gift_value" => 5,
                    "commission_gift_desc_ar" => "يمكن لمالك الغرفة الحصول على 5% نسبة من الهدايا المرسلة داخل الغرفة", // gift commission from room
                    "commission_gift_desc_en" => 2.5, // gift commission from room
                    "entrance_effect" => 1,
                    "entrance_effect_value" => 1,
                    "entrance_effect_desc_ar" => "يمكنك إظهار تأثيرات الدخول عند الدخول لأي غرفة", // entrance effect
                    "entrance_effect_desc_en" => 1, // entrance effect
                    "colored_name" => 1,
                    "colored_name_value" => 1,
                    "colored_name_desc_ar" => "يكون اسم المستخدم بنفس لون هذه الاستقراطية علي حسب الاختيار", // colored_name
                    "colored_name_desc_en" => 1, // colored_name
                    "special_gift" => 1,
                    "special_gift_value" => 0,
                    "special_gift_count" => 11,
                    "special_gift_desc_ar" => "يحصل المستخدم علي هدية خاصة ( تاج ) بقيمة 299 كوينز عدد 11 تاج", // special gift
                    "special_gift_desc_en" => 0, // special gift
                    "arsto_card" => 1,
                    "arsto_card_value" => 1,
                    "arsto_card_desc_ar" => "بطاقة الأرستقراطي في الغرفة ( شكل البروفيل في الغرفة )", // arsto card desc
                    "arsto_card_desc_en" => "1", // arsto card desc
                    "vip_vehicle" => 1,
                    "vip_vehicle_value" => 0,
                    "vip_vehicle_desc_ar" => "يمكنك إظهار هذه المركبة عند دخول الغرفة، يمكنك تعديل ذلك في خزنة الزينة", // vehicle
                    "vip_vehicle_desc_en" => "", // vehicle
                    "colored_messages" => 1,
                    "colored_messages_value" => 0,
                    "colored_messages_desc_ar" => "الرسائل التي أرسلت ستكون ملونة", // colored_message
                    "colored_messages_desc_en" => "", // colored_message
                    "room_password"=> 1,
                    "room_password_value"=> 0,
                    "room_password_desc_ar"=> "يمكن لمالك الغرفة اغلاق غرفته بالرقم السري المكون من  6 ارقام", // room password
                    "room_password_desc_en"=> "", // room password
                    "anti-kick" => 1,
                    "anti-kick_value" => 0,
                    "anti-kick_desc_ar" => "لا يمكن لأي أحد طردك من الغرفة", // anti kick
                    "anti-kick_desc_en" => "", // anti kick
                    "hide_country" => 1,
                    "hide_country_value" => 0,
                    "hide_country_desc_ar" => "سيتم إظهار دولتك كغير معروفة في صفحتك الشخصية", // hide country
                    "hide_country_desc_en" => "", // hide country
                    "anti-ban-chat"=> 1,
                    "anti-ban-chat_value"=> 0,
                    "anti-ban-chat_desc_ar"=> "لا يمكن لأي أحد حظرك من الكتابة في الغرفة", // ban chat
                    "anti-ban-chat_desc_en"=> "", // ban chat
                    "exp" => 1,
                    "exp_value" => 1.5,
                    "exp_value_desc_ar" => "1.5 مرة زيادة في نقاط الخبرة", // exp % gain
                    "exp_value_desc_en" => "", // exp % gain
                    "support_first" => 1,
                    "support_value" => 0,
                    "support_desc_ar" => "",  // support desc
                    "support_desc_en" => "خدمة العملاء تحل استجابتك أولا",  // support desc
                    "upload_background" => 1,
                    "upload_background_value" => 0,
                    "upload_background_desc_ar" => "تحميل الموضوع، ويمكنك استخدام كل الموضوعات مجاناً", // upload background desc
                    "upload_background_desc_en" => "", // upload background desc
                    "daily_login_reward" => 1,
                    "daily_login_reward_value" => 4000,
                    "daily_login_reward_desc_ar" => "كوينزات أكثر لتسجيل الدخول اليومي ( 4000 كوينز يوميا )",
                    "daily_login_reward_desc_en" => "",
                ]
            )
        ]);
    }
}
